# Generated by Django 3.1.2 on 2020-10-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20201020_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='C:\\Users\\Mahdi\\PycharmProjects\\ImageUpload\\temp'),
        ),
    ]
