# Generated by Django 3.1.2 on 2020-10-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20201026_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='C:\\Users\\Mahdi\\PycharmProjects\\ImageUpload\\mediafiles'),
        ),
    ]
